name: checks
on:
  - push
  - pull_request
  - workflow_call

jobs:
  lint:
    uses: boringnode/.github/.github/workflows/lint.yml@main

  typecheck:
    uses: boringnode/.github/.github/workflows/typecheck.yml@main

  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: queue_test
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: corepack enable

      - name: Setup Node.js cache
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          PG_HOST: localhost
          PG_PORT: 5432
          PG_USER: postgres
          PG_PASSWORD: postgres
          PG_DATABASE: queue_test
